### ISSUE TITLE
后台中某些设置无法进入，

### ISSUE THREAD

**Issue by 9527tech** [ruibaby/halo#12]
抱歉，，我又来，打扰你了。:smile:，首先，现在，我遇到两个问题，额，
就在刚刚，我升级到了0.0.3，进入后台，发现:点击用户下的个人资料会跳到login页面;点击文章下的标签也会跳到login页面，嗯，暂时就发现这两个会跳，。。:sweat:
然后第二个问题是友链没显示，，，，
嗯嗯，就这两问题，，

**Comment by ruibaby** [comment]
不是吧，没遇到这样的问题啊

**Comment by 9527tech** [comment]
唉，可能是我这边的问题吧，，唉，头疼，

**Comment by ruibaby** [comment]
宝塔的默认反向代理配置确实有问题

**Comment by 9527tech** [comment]
唉，直接裸奔算了，，，:smile:

**Comment by ruibaby** [comment]
你在群里吗？我发过一个配置，我测试过没有任何问题的

**Comment by 9527tech** [comment]
@ruibaby 嗯嗯，我在，

**Comment by 9527tech** [comment]
我，，找到原因了，是我自己的问题:宝塔的nginx反代里有关于缓存的配置，默认好像没开，但我手贱的开了，然后，，，刚才我那些注释了就，行了，，，:grinning:

**Comment by 9527tech** [comment]
@ruibaby 这次，真的打扰了，不好意思，:relieved:，

**Comment by ruibaby** [comment]
@9527tech 解决了就好

**Comment by 9527tech** [comment]
@ruibaby 好了，感谢大佬，希望这项目越来越好，:+1:

**Comment by ruibaby** [comment]
@9527tech 感谢你的资瓷，不过需要你们的反馈
