### ISSUE TITLE
找不到上传后的图片

### ISSUE THREAD

**Issue by dreamlandfeeling** [ruibaby/halo#15]
显示图片上传成功但是显示不出来
根据上传路径也找不到图片

**Comment by ruibaby** [comment]
请再说得详细一样，比如是在本地还是服务器，服务器的版本等

**Comment by dreamlandfeeling** [comment]
上传文件[9ec12ee7-65b5-4cc5-9900-d2ec6185b620180624174351556.jpg]到[D:\test\%e9%a1%b9%e7%9b%ae\halo-master\target\classes\upload\2018\6]成功

是本地的

**Comment by ruibaby** [comment]
@dreamlandfeeling 我去Windows下试试

**Comment by ruibaby** [comment]
@dreamlandfeeling 刚刚在Win10上试了下，没有问题的。

**Comment by dreamlandfeeling** [comment]
..知道原因了。。我的锅。因为我路径有中文。。所以。。
D:\test\%e9%a1%b9%e7%9b%ae\halo-master\target\classes
D:\test\项目\halo-master\target\classes

**Comment by ruibaby** [comment]
@dreamlandfeeling 解决了就好。
