### ISSUE TITLE
文章自动保存草稿定时器没有关闭

### ISSUE THREAD

**Issue by AlanDelon** [ruibaby/halo#17]
定时器没有关闭导致一直执行

**Comment by ruibaby** [comment]
恩？不是很懂你的意思，能再说清楚点吗？

**Comment by AlanDelon** [comment]
post编辑页面的，setinterval(autoPush, 30000)，这个东西需要关闭的，不然离开这个编辑页面后还是一直循环调用autoPush。只不过中间代码报错了请求不到后台。

**Comment by ruibaby** [comment]
@AlanDelon 好的，我知道了
