### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by bigsu** [ruibaby/halo#19]
最近也考虑搭建一个自己的博客系统，很喜欢这个项目，感谢作者开源，会持续关注，希望作者能多加入些主题，比如NexT这种极简风格的，期待七牛云功能的上线

**Comment by ruibaby** [comment]
谢谢你的支持。
by the way，Next一直在计划之中，七牛云/又拍云也在计划之内。

**Comment by bigsu** [comment]
666
