### ISSUE TITLE
项目导入到eclipse异常 log cannot be resolved

### ISSUE THREAD

**Issue by diaocoin** [ruibaby/halo#28]
我用的编辑器是eclipse  jdk1.7和1.8都试过啦，项目导入后编译不过，所有log.info的地方抛  “log cannot be resolved”； 看import也未发现类中有log引用，也未看到代码中有log的实例， 想请教一下是什么原因？

**Comment by ruibaby** [comment]
@diaocoin 注意看readme和wiki，需要安装lombok插件。
