### ISSUE TITLE
项目启动后会循环重定向

### ISSUE THREAD

**Issue by cuitpanfei** [ruibaby/halo#29]
clone 源码后idea启动正常。
![image](https://user-images.githubusercontent.com/28720003/44219704-4db73080-a1af-11e8-9905-d4ac67ff33b5.png)
但是访问url时会循环重定向到install
![image](https://user-images.githubusercontent.com/28720003/44219784-7808ee00-a1af-11e8-83d2-a14a18c6c3ec.png)

**Comment by ruibaby** [comment]
@cuitpanfei 执行mvn clean，然后profile选择dev再运行看看。

**Comment by cuitpanfei** [comment]
还是有问题。
启动正常
![default](https://user-images.githubusercontent.com/28720003/44300728-77529200-a33e-11e8-9eed-ebdde11c0565.png)

在访问地址的时候循环重定向
![default](https://user-images.githubusercontent.com/28720003/44300683-cd730580-a33d-11e8-9235-6c4796d60a30.png)

**Comment by ruibaby** [comment]
@cuitpanfei 不应该啊，clean之后然后在运行是没有问题的，你把target目录给我看看

**Comment by cuitpanfei** [comment]
![default](https://user-images.githubusercontent.com/28720003/44300862-30fe3280-a340-11e8-85bc-f67129005050.png)

**Comment by ruibaby** [comment]
@cuitpanfei 这....貌似木有问题啊

**Comment by cuitpanfei** [comment]
我也觉得，然而它实实在在发生了。对了我用的idea，这个不会有些影响吧

**Comment by cuitpanfei** [comment]
我采用的源码运行的，没试过打包后的。

**Comment by ruibaby** [comment]
@cuitpanfei 我也是用的idea丫，之前也有人出现这样的问题，我让他们选择dev之后重新运行就可以了啊，而且你启动居然用了44秒？一般5-10秒就行了啊。

**Comment by cuitpanfei** [comment]
我把h2改成了mysql

**Comment by ruibaby** [comment]
@cuitpanfei 你试试用prod打包，然后在运行jar试试，打包完成后jar在target/dist/halo里。

**Comment by cuitpanfei** [comment]
![default](https://user-images.githubusercontent.com/28720003/44301070-b8997080-a343-11e8-897f-a26fdacb7b6d.png)

**Comment by ruibaby** [comment]
@cuitpanfei 稍等一下，我看看是不是我最近提交的代码导致的

**Comment by cuitpanfei** [comment]
有点晚了，先这样吧。我自己也看看，我估计不是代码上的问题。这情况就是找不到install视图然后跳转到500，然后500被拦截到install，然后就循环重定向了。

**Comment by ruibaby** [comment]
@cuitpanfei 刚刚我把数据库删了，target也清除了，没有发现问题，你再检查一下是不是其他原因导致的

**Comment by lhzlg3368** [comment]
我表示我也遇到了同样的问题

**Comment by ruibaby** [comment]
@lhzlg3368 怎么导入的项目？

**Comment by cuitpanfei** [comment]
应该是修改过yaml文件，我删掉我yaml的重新pull过后就没有问题了。但是之前到底是改了哪里我也不清楚

**Comment by lhzlg3368** [comment]
@ruibaby 下载源码，使用ideaJ

**Comment by ruibaby** [comment]
@lhzlg3368 是用的import还是open？

**Comment by lhzlg3368** [comment]
@ruibaby 下载源码，然后用ideaJ open 不是导入。
