### ISSUE TITLE
大佬，把代码找了个遍，没看见java代码里怎么处理pjax请求的，请问你这博客开启pjax后后台怎么知道一个请求是pjax还是普通请求呢？

### ISSUE THREAD

**Issue by tomoya92** [ruibaby/halo#31]
只见在_macro.ftl文件里引入了js，如果开启pjax的话把a标签都改成了pjax请求，但java代码里没见到这方面的处理，求指点

**Comment by ruibaby** [comment]
没有把所有a标签弄成pjax请求，a标签的data-pjax="true"的时候才用pjax请求，如：<a data-pjax="true" href="/admin">，另外，不需要Java处理pjax请求。

**Comment by tomoya92** [comment]
那如果一个页面是从浏览器输入网址进入的怎么渲染呢？是带着layout还是不带呢？

**Comment by ruibaby** [comment]
@tomoya92 直接渲染啊，对了，我用的插件是jquery.pjax，你可以搜索一下看看相关的使用方法

**Comment by tomoya92** [comment]
服务端还是要处理一下的，我已经弄出来了，layout 页面要建两个，一个是正常刷新页面的布局，一个是pjax请求要用到的layout，然后在拦截器里输出，这样即使是pjax请求的链接，直接刷新布局也不会消失

![untilte](https://user-images.githubusercontent.com/6915570/44384504-fe765480-a54e-11e8-92ed-4a139340f7b7.gif)

这是我整理的博客：https://tomoya92.github.io/2018/08/21/spring-boot-freemarker-pjax/

PS： 我用的也是jquery.pjax

**Comment by ruibaby** [comment]
@tomoya92 其实是一样的
