### ISSUE TITLE
某些路径支持一下中文呗？

### ISSUE THREAD

**Issue by magical-l** [ruibaby/halo#34]
git clone，放在了“源码”目录下面，用intellij idea打开工程并运行之，结果在后台安装主题时出错了：主题被上传到了与“源码”同级的%bla%bla%bla%bla目录下，就访问不到了。这些blabla你懂的……urlEncode("源码")。不知道有没有其他地方有此类问题。

**Comment by ruibaby** [comment]
@magical-l 抱歉，我认为没有必要。

**Comment by magical-l** [comment]
那好歹加个说明？就像“改名为xx，改名为xx，改名为xx”

**Comment by ruibaby** [comment]
@magical-l 你的意思是？ 哪里改名？

**Comment by magical-l** [comment]
> @magical-l 你的意思是？ 哪里改名？

哦，不是，我是说你提供的几个模板里面都有一句类似于“下载后把文件夹改名为xx”的重复3遍的话，哈哈。类似于这种提示。

**Comment by ruibaby** [comment]
@magical-l 哦，现在不需要了，直接上传就行
