### ISSUE TITLE
metaweblog api 实现

### ISSUE THREAD

**Issue by dowhilenet** [ruibaby/halo#35]
是否之后会考虑 metaweblog api 的实现。

**Comment by ruibaby** [comment]
@dowhilenet 没听说过，能简单解释一下吗？

**Comment by ruibaby** [comment]
@dowhilenet 好的，我知道了，会考虑的

**Comment by dowhilenet** [comment]
[MetaWeblog 和 XML-RPC](https://www.ibm.com/developerworks/cn/xml/x-metablog/index.html#artrelatedtopics)

有空的话我打算参考[b3log](https://github.com/b3log/solo/blob/master/src/main/java/org/b3log/solo/api/MetaWeblogAPI.java)来实现一下。

想实现这个的主要原因是因为通常习惯在 markdown 的客户端编辑器上来写博客。很多编辑器是支持通过MetaWeblog 将博客发布到站点上的。

优先级可以先往后排一下。

觉得你这个项目还是不错的，正打算熟悉一下代码学习学习。

**Comment by ruibaby** [comment]
@dowhilenet 好的，欢迎贡献代码

**Comment by Mrered** [comment]
这个功能现在实现了嘛？

**Comment by ruibaby** [comment]
> 这个功能现在实现了嘛？

想知道目前有哪些客户端支持这个协议呢？感觉这个协议用的不是很多的样子。

如果有这个需求，我建议再提交一个 issue，看看社区是否有人愿意通过插件实现一下。

**Comment by Mrered** [comment]
> > 这个功能现在实现了嘛？
> 
> 想知道目前有哪些客户端支持这个协议呢？感觉这个协议用的不是很多的样子。
> 
> 如果有这个需求，我建议再提交一个 issue，看看社区是否有人愿意通过插件实现一下。

[MWeb - 专业的Markdown写作、记笔记、静态博客生成软件 - MWeb](https://zh.mweb.im/)

**Comment by ruibaby** [comment]
Hi @Mrered , 如果是想在本地客户端编写文章发布到 Halo 的话，目前我个人正在实现 Obsidian 和 VSCode 的发布插件，应该也能满足在本地客户端发布的需求。

不过，我们对 MetaWeblog API 保持开放态度，期望社区有人愿意参与实现。

**Comment by Mrered** [comment]
> Hi @Mrered , 如果是想在本地客户端编写文章发布到 Halo 的话，目前我个人正在实现 Obsidian 和 VSCode 的发布插件，应该也能满足在本地客户端发布的需求。
> 
> 不过，我们对 MetaWeblog API 保持开放态度，期望社区有人愿意参与实现。

！要是有 Obsidian 发布插件那就再好不过了！感谢！！！

**Comment by ruibaby** [comment]
Hi @Mrered ，现在社区发布了一个 VSCode 的插件，可以直接同步 Markdown 文档到 Halo（包括引用的本地图片），可以尝试一下：https://marketplace.visualstudio.com/items?itemName=halo-dev.halo

> 至于 Obsidian，目前卡在了图片上传的部分，可能还需要一些时间。

**Comment by Mrered** [comment]
> Hi @Mrered ，现在社区发布了一个 VSCode 的插件，可以直接同步 Markdown 文档到 Halo（包括引用的本地图片），可以尝试一下：https://marketplace.visualstudio.com/items?itemName=halo-dev.halo
> 
> > 至于 Obsidian，目前卡在了图片上传的部分，可能还需要一些时间。

我目前使用 Piclist 进行上传操作，使用到了以下特性：

- 自动转换格式为 webp
- 使用基于 YOURLS 的自建短链系统
- 自定义输出图片格式为

```markdown
<p style="text-align: center"><img loading="lazy" src="<图片链接>" width="90%" height="auto" style="display: inline-block"></p>
```

希望可以考虑以上特性！
