### ISSUE TITLE
User-Agent过长会导致插入失败

### ISSUE THREAD

**Issue by nan-lou** [ruibaby/halo#43]
![tim 20181108180154](https://user-images.githubusercontent.com/22869648/48191570-65eab600-e380-11e8-9ba2-a8d111db016f.png)

**Comment by ruibaby** [comment]
好的，下个提交修复

**Comment by ruibaby** [comment]
已解决https://github.com/ruibaby/halo/commit/efdde9327c791e87d53ab1bf96c8f49dcd539a47
