### ISSUE TITLE
选择头像分辨率不对时会导致布局错误

### ISSUE THREAD

**Issue by nan-lou** [ruibaby/halo#44]
![image](https://user-images.githubusercontent.com/22869648/48199446-fdf39a00-e396-11e8-8ab5-6184ee2d0635.png)
（另外上传图片的时候好像不能进行切割QWQ）

**Comment by ruibaby** [comment]
@nan-lou 好的，下个提交修复

**Comment by ruibaby** [comment]
这个不管啦，adminlte就是那样设定的，如果我指定图片的长宽的话，侧边栏收缩的时候，图片显示也会有问题，你选择长宽相同的图片就行啦。
