### ISSUE TITLE
Markdown 支持程度不够

### ISSUE THREAD

**Issue by kaixinbaba** [ruibaby/halo#50]
我没有测试所有的markdown，但是一些希腊字母和数学公式（比如sum）就不支持
![image](https://user-images.githubusercontent.com/22809336/48827285-cb3e9e00-eda7-11e8-8aff-88a0fa259b44.png)
![image](https://user-images.githubusercontent.com/22809336/48827289-ced22500-eda7-11e8-9038-682c0c0610ea.png)
预览后：
![image](https://user-images.githubusercontent.com/22809336/48827298-d7c2f680-eda7-11e8-893f-dea87e0ddfbf.png)
![image](https://user-images.githubusercontent.com/22809336/48827306-db567d80-eda7-11e8-83f2-0c2122e3822a.png)

**Comment by ruibaby** [comment]
@namxedoc 用的是markdown标准库，这么多人需要支持数学公式，那我就想办法加一个吧。

**Comment by namxedoc** [comment]
感谢大大～

**Comment by ruibaby** [comment]
已支持。https://github.com/ruibaby/halo/commit/efd874b3d6ca24ec2a84796f8b52017bfa560705

**Comment by namxedoc** [comment]
好像还是有点小问题。。
![image](https://user-images.githubusercontent.com/22809336/49712531-daff2300-fc7f-11e8-9b33-84e4f541f364.png)
绿框的是ok了，红框还是有问题，这篇文章原文我是写在csdn上的，这些符号都能被识别的
我发现，gamma 这个小符号是没问题的，但是公式就会有问题 除非 你在公式前后加上 标签 像这样：
![image](https://user-images.githubusercontent.com/22809336/49712564-100b7580-fc80-11e8-8738-326281529d21.png)
中间的数学公式就会被markdown语法解析，不然就是普通的字符串，求大大帮忙看下

**Comment by namxedoc** [comment]
。。接上一个comment，而且 ok只是预览 ok，但是发布之后 到浏览的页面 那些绿框并没有ok，像这样：
![image](https://user-images.githubusercontent.com/22809336/49712651-77c1c080-fc80-11e8-89de-cc81b052e5bc.png)
麻烦大大了。。。

**Comment by namxedoc** [comment]
![image](https://user-images.githubusercontent.com/22809336/49737718-846a0700-fcc8-11e8-8a7d-8bb27b6ede1d.png)
next 主题我已经安装好了，zip本地安装或者远程git安装都试过了，docker 也restart过了，但是换到next主题的话，访问主页就会变成空白的（只有一根黑线），像这样：
![image](https://user-images.githubusercontent.com/22809336/49737860-d743be80-fcc8-11e8-92dc-1e4d0598d231.png)
不小心出另一个issue了，难道是我姿势不对吗

**Comment by namxedoc** [comment]
麻烦大大了。。。。我也不是很急的，大大注意身体

**Comment by ruibaby** [comment]
@kaixinbaba https://github.com/ruibaby/halo/commit/7d452d5ca94768ecf79b556a9a67bbee4db99a38，已经提交了，我去网上搜了很多mathjax的公式，都已经完美支持了，过两天我再发布版本。

**Comment by ruibaby** [comment]
@kaixinbaba 已经提交了，我去网上搜了很多mathjax的公式，都已经完美支持了，过两天我再发布版本。https://github.com/ruibaby/halo/commit/7d452d5ca94768ecf79b556a9a67bbee4db99a38

**Comment by kaixinbaba** [comment]
又要求助大大了。。
首先我安装了并启用了next主题
![image](https://user-images.githubusercontent.com/22809336/52534522-70508d80-2d7d-11e9-90a9-c8dc5289d43c.png)
可以看到在对比和预览模式中，公式被显示的完好
![image](https://user-images.githubusercontent.com/22809336/52534527-92e2a680-2d7d-11e9-8ec8-c10650741eeb.png)
但是前台显示还是不行
![image](https://user-images.githubusercontent.com/22809336/52534530-aa219400-2d7d-11e9-8f0a-0cde0905f5cd.png)
用的部署方式也是 主页下readme中的docker方式
![image](https://user-images.githubusercontent.com/22809336/52534549-e7862180-2d7d-11e9-93c8-c85e2c645f3c.png)
docker 拉取的镜像是9天前创建的，而大大之前跟我提到的commitid是17天前，应该是最新的了吧
![image](https://user-images.githubusercontent.com/22809336/52534557-0dabc180-2d7e-11e9-86f2-edb2d0157cc3.png)
求助大大，所以是我姿势不对还是哪里不对？我想要的是前台也完美显示markdown公式～麻烦了

**Comment by ruibaby** [comment]
> 又要求助大大了。。
> 首先我安装了并启用了next主题
> ![image](https://user-images.githubusercontent.com/22809336/52534522-70508d80-2d7d-11e9-90a9-c8dc5289d43c.png)
> 可以看到在对比和预览模式中，公式被显示的完好
> ![image](https://user-images.githubusercontent.com/22809336/52534527-92e2a680-2d7d-11e9-8ec8-c10650741eeb.png)
> 但是前台显示还是不行
> ![image](https://user-images.githubusercontent.com/22809336/52534530-aa219400-2d7d-11e9-8f0a-0cde0905f5cd.png)
> 用的部署方式也是 主页下readme中的docker方式
> ![image](https://user-images.githubusercontent.com/22809336/52534549-e7862180-2d7d-11e9-93c8-c85e2c645f3c.png)
> docker 拉取的镜像是9天前创建的，而大大之前跟我提到的commitid是17天前，应该是最新的了吧
> ![image](https://user-images.githubusercontent.com/22809336/52534557-0dabc180-2d7e-11e9-86f2-edb2d0157cc3.png)
> 求助大大，所以是我姿势不对还是哪里不对？我想要的是前台也完美显示markdown公式～麻烦了

在next的主题设置里把mathjax启用

**Comment by kaixinbaba** [comment]
我在next的主题设置里没有找到mathjax。。但是我在Material主题里找到了并启用了，效果是ok的。。。什么主题我是无所谓的～反正 感谢大大了～拜个晚年，祝大大猪事顺利

**Comment by ruibaby** [comment]
@kaixinbaba 好的，晚点看看NexT的mathjax
