### ISSUE TITLE
主题有问题

### ISSUE THREAD

**Issue by xuyixia** [ruibaby/halo#51]
vno主题的设置功能报错，大佬

**Comment by ruibaby** [comment]
@xuyixia 报的啥错

**Comment by lich1n** [comment]
我下载了https://gitee.com/babyrui/hux-halo

处的主题，启用后页面都跳500了，怎么解决

![image](https://user-images.githubusercontent.com/24382458/51236400-037bea80-19ad-11e9-9278-c32f9a6a16bb.png)
http://dawnsouth.com

**Comment by ruibaby** [comment]
@lich1n 其他主题有问题吗？

**Comment by lich1n** [comment]
![image](https://user-images.githubusercontent.com/24382458/51236920-4db19b80-19ae-11e9-9392-c01a9e3a99e7.png)


有的，我下了三个，在主题管理中都无法显示简略图，刚看后台报错
