### ISSUE TITLE
建议使用百度ueditor作为富文本框

### ISSUE THREAD

**Issue by wanbao666** [ruibaby/halo#54]
![image](https://user-images.githubusercontent.com/39851813/48965701-1d2c3180-effd-11e8-80a5-81cd5c9763f1.png)

ueditor 功能更丰富，效果更好。

**Comment by ruibaby** [comment]
@wanbao666 如果非要支持富文本编辑的话，应该也不会选择ueditor，太重了，而且ui不好看，抱歉，原谅我的偏执。

**Comment by wanbao666** [comment]
纯属个人拙见，只是觉得ueditor对照片的处理比较好，可以直接复制进去。哈哈哈。尊重原创。



wanbao666@qq.com
 
发件人： RYAN0UP_
发送时间： 2018-11-24 16:40
收件人： ruibaby/halo
抄送： wanbao666; Mention
主题： Re: [ruibaby/halo] 建议使用百度ueditor作为富文本框 (#54)
@wanbao666 如果非要支持富文本编辑的话，应该也不会选择ueditor，太重了，而且ui不好看，抱歉，原谅我的偏执。

**Comment by dandelion1000** [comment]
粘贴图片功能很容易做呀

**Comment by ruibaby** [comment]
@dandelion1000 暂时不考虑支持富文本编辑器，就算支持，也不会用ueditor
