### ISSUE TITLE
建议在dockerfile里设置时区

### ISSUE THREAD

**Issue by gongjunhao** [ruibaby/halo#55]
直接拉取镜像，启动运行服务，发现系统记录的时间总是差8个小时，猜测是时区没有设置为东八区，建议在dockerfile里增加时区设置或参数指定
```
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

**Comment by ruibaby** [comment]
好的，下个版本修复

**Comment by ruibaby** [comment]
已修复，https://github.com/ruibaby/halo/commit/12e8e6865589e9cf0cdbc858d301cf82cdab82cd
