### ISSUE TITLE
在Pom.xml中导入maven-assembly-plugin插件，报错找不到此插件，我哪里写错了吗？

### ISSUE THREAD

**Issue by StarSky1** [ruibaby/halo#58]
![q p vx hmwj zj5 40xv0](https://user-images.githubusercontent.com/31197138/49569787-dbda4100-f96f-11e8-9f5a-64f5fced5acc.png)

在maven的pom.xml文件中添加这个插件时，报错找不到此插件，这是什么问题啊，重新导入了好几次依赖都没用

**Comment by ruibaby** [comment]
你换个maven镜像源试试。一般出现这种依赖下载错误，都是网络的问题。

**Comment by StarSky1** [comment]
用的阿里的镜像，换网络之后，还是不行

**Comment by ruibaby** [comment]
不应该吧。看看你本地仓库有没有这个依赖

**Comment by StarSky1** [comment]
本地仓库没有，不过刚刚解决了。
我在Pom文件中加入下面这个插件，其他配置删掉,下载成功了，恢复到原来的pom文件也不报错了，但具体原因还不知道。
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-assembly-plugin</artifactId>
    <version>3.1.0</version>
</plugin>
```
