### ISSUE TITLE
没有找到API的正确食用方式

### ISSUE THREAD

**Issue by ChenViVi** [ruibaby/halo#59]
如果项目部署到了[http://localhost:8090](http://localhost:8090)，那么访问[http://localhost:8090/api/archives/year](http://localhost:8090/api/archives/year)，不是应该能够得到根据年份归档文章的json信息吗？而实际上会返回404页面。我使用了docker和运行源码两种方式，情况都是这样。是不是本来要返回json信息而实际上去尝试解析了视图，而对应路由的视图根本不存在导致的？

**Comment by ruibaby** [comment]
@ChenViVi 因为你没在后台打开api的开关....
