### ISSUE TITLE
CUP沾满问题

### ISSUE THREAD

**Issue by NingSo** [ruibaby/halo#63]
![image](https://user-images.githubusercontent.com/12245385/50153760-57d67080-0302-11e9-8a36-634a6e2c47c0.png)
 如题：
 **systemctl start halo** 之后服务器巨卡，看了一下top。发现cpu被沾满了。停止该halo服务恢复正常，请问这个怎么解？？

**Comment by ruibaby** [comment]
@NingSo 这....还真不知道，从没遇到过
