### ISSUE TITLE
Halo博客备份功能失败，Backup database failed

### ISSUE THREAD

**Issue by LianWilliam** [ruibaby/halo#64]
/var/log/messages 日志文件报错如下：

Dec 19 09:29:17 Mybwh java: 2018-12-19 09:29:17.508 ERROR 26701 --- [ XNIO-2 task-10] c.r.h.w.c.admin.BackupController         : Backup database failed: File [/root/halo/halo.mv.db] not exist!

[/root/halo/halo.mv.db 这个文件要不是自动代码自动导出的吗？需要手动导出么？

**Comment by LianWilliam** [comment]
补充界面报错，使用的是Halo最新版本
![image](https://user-images.githubusercontent.com/35838730/50193402-67d96900-0371-11e9-9a01-08c61616df11.png)

**Comment by ruibaby** [comment]
@LianWilliam 是使用的mysql数据库还是？

**Comment by LianWilliam** [comment]
mysq 5.5，mysql数据库和Halo安装目前在一台服务器上

**Comment by ruibaby** [comment]
@LianWilliam 暂不支持mysql备份

**Comment by myflytop** [comment]
好吧   还以为只是我的问题  其实这个可以说明一下

**Comment by ruibaby** [comment]
@myflytop 嗯，是我的问题

**Comment by myflytop** [comment]
这边可以反馈一个浏览器兼容的问题吗？

**Comment by ruibaby** [comment]
@myflytop 嗯，什么问题

**Comment by myflytop** [comment]
@ruibaby  用百度浏览器  弹窗直接挂了  就是那个附件页  一闪而过  然后出现空白

**Comment by ruibaby** [comment]
@myflytop 刚刚下了个试了下，没有复现

**Comment by myflytop** [comment]
@ruibaby  chorme是正常的     
![1 1](https://user-images.githubusercontent.com/36969398/53281729-71fc5700-3768-11e9-9d1f-f139e3a0b4a2.png)
百度浏览器就这样 
![1 2](https://user-images.githubusercontent.com/36969398/53281733-87718100-3768-11e9-8202-467b0378d79e.png)
