### ISSUE TITLE
文章数量32 有性能问题？

### ISSUE THREAD

**Issue by wenthywang** [ruibaby/halo#68]
本人部署了一套halo 后台，和小程序 ，发现请求接口达到了3-4s ，使用postman请求也是，我试过删掉文章，再重新请求，发现竟然毫秒级，这是不是性能问题呢？

ps:
机器：2g内存 1核
使用nginx 做代理请求转发
使用docker 部署

**Comment by ruibaby** [comment]
有可能是的，因为那个小程序所调用的接口是调用的归档的接口，不是直接调用的 `/posts/page/1` 这种，归档会有多个查询，所以性能会差点。

**Comment by wenthywang** [comment]
@ruibaby 那这个可以优化吗？

**Comment by ruibaby** [comment]
@wenthywang 有空看看

**Comment by ruibaby** [comment]
报错了，你去数据库把halo_menus表里的数据全删了，重启就行了。

**Comment by wenthywang** [comment]
好的 我搞下

**Comment by wenthywang** [comment]
尴尬了 没用过这个数据库 不知道怎么连

**Comment by ruibaby** [comment]
@wenthywang https://ryanc.cc/archives/how-to-use-h2-database

**Comment by wenthywang** [comment]
问题来了 docker 部署 docker 下面这个参数  web-allow-others 应该是false

**Comment by wenthywang** [comment]
Sorry, remote connections ('webAllowOthers') are disabled on this server.

**Comment by ruibaby** [comment]
@wenthywang 去docker容器里面改吧。

**Comment by wenthywang** [comment]
好的

**Comment by wenthywang** [comment]
删掉了，但是还是空白，这次好一点 有博客标题，文章都看不到，
![image](https://user-images.githubusercontent.com/15195159/50418442-55c26380-0866-11e9-9a7f-03baaf94554e.png)

**Comment by wenthywang** [comment]
![image](https://user-images.githubusercontent.com/15195159/50418456-683c9d00-0866-11e9-89a7-ecabd0e866f2.png)

**Comment by ruibaby** [comment]
@wenthywang 在主题设置里，把每个tab的设置都保存一下试试

**Comment by wenthywang** [comment]
保存了 没报错了 但还是空白

**Comment by wenthywang** [comment]
![image](https://user-images.githubusercontent.com/15195159/50418608-57405b80-0867-11e9-9d48-c1a547f86536.png)
我看还是有 报错，这不是两个一样的请求，为撒拼url 拼错了？

**Comment by ruibaby** [comment]
@wenthywang 你暂时先用其他主题吧，有空我再看看Next。

**Comment by wenthywang** [comment]
好的，现在也就只有默认的主题能用了

**Comment by ruibaby** [comment]
@wenthywang 其他主题都行。
