### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by asche910** [ruibaby/halo#70]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

写文章的markdown编辑器，引用外部图片，图片无法显示。
比如： ![image](https://img2018.cnblogs.com/blog/1470456/201812/1470456-20181206183046416-842826862.jpg)

图片链接没有问题

**Comment by asche910** [comment]
> @asche910 cnblog有防盗链吧。

我在别的地方也同样引用过的csdn的图片，没有出现问题

**Comment by asche910** [comment]
> > @asche910 cnblog有防盗链吧。
> 
> 我在别的地方也同样引用过的csdn的图片，没有出现问题

说错了  是cnblog

**Comment by ruibaby** [comment]
@asche910 不是吧，我再看看，之前有人也出现过，但是我用我博客就没问题。

**Comment by asche910** [comment]
刚刚看了下， 返回403，应该就是防盗链吧。别的网站在引用cnblog图片时，会重新上传到自己服务器上。
