### ISSUE TITLE
Vno-Halo  中的菜单中的归档链接跳转为500

### ISSUE THREAD

**Issue by ANyedt** [ruibaby/halo#74]
**我确定我已经查看了** (标注`[ x]`为`[x]`)

- [ ] [Halo 使用文档](https://docs.halo.run/)
- [ ] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[x ]`为`[x]`)

- [ x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
找不到归档模板抛出的异常。
