### ISSUE TITLE
API整合Swagger

### ISSUE THREAD

**Issue by leijue222** [ruibaby/halo#75]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [√ ] [Halo 使用文档](https://docs.halo.run/)
- [√ ] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [√ ] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x ] BUG 反馈
- [ √] 添加新的特性或者功能
- [x ] 请求技术支持
请问可以考虑把API整合Swagger吗？现在的API文档不太好查阅。

**Comment by ruibaby** [comment]
好的，我会考虑的，但是并不是特别想用Swagger，因为不想多加一个依赖。但是我会用其他文档生成工具生成文档的。

**Comment by leijue222** [comment]
嗯，谢谢。不管是Swagger或者别的工具都行，主要能让查阅API更方便一些就再好不过了。

**Comment by JohnNiang** [comment]
已经添加 Swagger 的支持！

see: <https://github.com/halo-dev/halo/commit/faa616d9928aefa25f05804585155826cf34741a>
