### ISSUE TITLE
文章发布后，再次进入文章编辑页面，文本框内仍有原文章内容

### ISSUE THREAD

**Issue by 1eeBoom** [ruibaby/halo#79]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

----
文章发布后，如果想要再写一篇新文章，再次进入文本编辑页面后发现上一篇发布的文章内容仍留在文本框内
![image](https://user-images.githubusercontent.com/26083044/51362415-7badf180-1b0e-11e9-8bfb-1916889ce699.png)

**Comment by ruibaby** [comment]
好的，下个版本修复

**Comment by 1eeBoom** [comment]
> 好的，下个版本修复

@ruibaby  好的，辛苦了！

**Comment by ruibaby** [comment]
@XuCpeng 更新一下试试，然后把浏览器缓存清掉，这个问题已经修复了。

**Comment by XuCpeng** [comment]
> 好的，下个版本修复

不但遗留有原文章内容，而且还会出现：修改文章时，编辑器内容与文章内容不匹配，发布后文章内容与编辑器也不匹配的问题。
比如，一篇文章修改了三次，当第三次提交的时候会显示第一次发布的内容。
比如，已发布的文章点击修改，会发现编辑器中的内容与文章有很大差异，而且这种差异每次修改都会出现，有时是少一句话，有时是md格式错误。即使调整正确，发布后也正确，当再次修改时，编辑器中的内容仍然错误。
复现视频：https://showmore.com/zh/u/3pik2we

**Comment by ruibaby** [comment]
@XuCpeng 这是啥浏览器，怎么感觉样式有点问题？ 已发布 草稿箱 回收站那里，有问题你先提，年后再修复

**Comment by XuCpeng** [comment]
> @XuCpeng 这是啥浏览器，怎么感觉样式有点问题？ 已发布 草稿箱 回收站那里，有问题你先提，年后再修复
ok,我先试试更新。Chrome 71

**Comment by ruibaby** [comment]
@XuCpeng 好，那里的样式找时间重写一下

**Comment by XuCpeng** [comment]
> @XuCpeng 好，那里的样式找时间重写一下

更新之后编辑器正常了

**Comment by ruibaby** [comment]
@XuCpeng 那就好
