### ISSUE TITLE
IDEA运行之后，一直提示404

### ISSUE THREAD

**Issue by sunny-baiye** [ruibaby/halo#80]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [] BUG 反馈
- [] 添加新的特性或者功能
- [x] 请求技术支持

我照着使用手册运行了halo，一直提示404，resource也设置成了Resource root，相关的依赖包，也自动下载好了。不知道哪里出了问题

**Comment by ruibaby** [comment]
@sunny-baiye 所有页面都是404吗？控制台有没有输出什么异常

**Comment by sunny-baiye** [comment]
所有页面都是404，控制台没有输出什么异常，用调试模式也是一样

**Comment by ruibaby** [comment]
@sunny-baiye 后台呢？也是吗？

**Comment by sunny-baiye** [comment]
我是把端口绑定改成了8080，然后启动的，访问地址http://localhost:8080，http://localhost:8080/admin，均无法访问

**Comment by ruibaby** [comment]
@sunny-baiye 根据你的描述 看不出来是怎么回事

**Comment by sunny-baiye** [comment]
![image](https://user-images.githubusercontent.com/11864716/51365176-047e5a80-1b1a-11e9-9760-22adf7315a70.png)
根目录下的pom.xml有几处是标红的，和这些有关系吗。

**Comment by ruibaby** [comment]
@sunny-baiye 没关系

**Comment by ruibaby** [comment]
@sunny-baiye 你试试打包运行
