### ISSUE TITLE
建议 Markdown 支持文章目录功能

### ISSUE THREAD

**Issue by 1eeBoom** [ruibaby/halo#81]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

----
对于一些长篇的文章，如果能够支持文章目录功能，阅读体验会提升不少。

**Comment by ruibaby** [comment]
这个是需要主题支持的，目前支持的有NexT Pinghsu Hux Story
