### ISSUE TITLE
写文章时选中附件中的图片链接有问题

### ISSUE THREAD

**Issue by lich1n** [ruibaby/halo#82]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

写文章的截图
![image](https://user-images.githubusercontent.com/24382458/51522394-35d19000-1e64-11e9-9b19-8346ca6ae912.png)

上面附件库选择图片时复制的链接
![](http://dawnsouth.com:8090/upload/2019/0/120190122160129959.png)
下面是F12找的该图片在附件库中加载时的链接
![](https://dawnsouth.com/upload/2019/0/120190122160129959_small.png)

F12中图片路径
![image](https://user-images.githubusercontent.com/24382458/51522435-500b6e00-1e64-11e9-9171-7846b8ad048f.png)

主要是后面“_small”被漏掉了，加上端口的问题我可以通过nginx解决

**Comment by lich1n** [comment]
点击附件图片的链接：
http://dawnsouth.com:8090/upload/2019/0/120190122160129959.png
正确的链接：
https://dawnsouth.com/upload/2019/0/120190122160129959_small.png

**Comment by ruibaby** [comment]
exm??? 加了_small的图片是缩略图啊，只做列表所用，你的意思是文章里面放的是压缩过的图片？

**Comment by lich1n** [comment]
好吧，我以为可选附件库的图片的
