### ISSUE TITLE
编辑器支持音乐视频

### ISSUE THREAD

**Issue by ruibaby** [ruibaby/halo#83]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

编辑器支持音乐视频

**Comment by ruibaby** [comment]
支持网易云音乐短代码:[music:id]: https://github.com/ruibaby/halo/commit/a84f7471112c0c50f0e71039c73313ceb7be579f

**Comment by wellmoonloft** [comment]
可以尝试对接一下腾讯云点播里面的视频，现在腾讯云点播实名之后就给一年免费，送空间+转码+CDN，并且https的流量也计入免费包
