### ISSUE TITLE
关于API增加分类目录的参数

### ISSUE THREAD

**Issue by wellmoonloft** [ruibaby/halo#84]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

目前是把这个博客当作小程序的一个内容提供平台，但是在接口的部分遇到了问题，现在能够看到的接口就是这样的接口https://XXXXX/api/archives/all，看上去使用的归档，只能根据年度来抓，不知道是不是可以提供根据分类目录的路径来抓？
如：

建筑 | building 
商户 | shops
文化 | culture 
生活 | life

https://XXXXX/api/list/building
https://XXXXX/api/list/shops
https://XXXXX/api/list/culture
https://XXXXX/api/list/life

**Comment by ruibaby** [comment]
@wellmoonloft 可以的，你获取文章列表其实可以用/api/posts/page/{{page}}，其他接口我会慢慢完善的，主要是现在用的人太少，没着重这一块。

**Comment by wellmoonloft** [comment]
> @wellmoonloft 可以的，你获取文章列表其实可以用/api/posts/page/{{page}}，其他接口我会慢慢完善的，主要是现在用的人太少，没着重这一块。

好的，我尝试一下，此外基于docker安装的后续升级问题有两种尝试：
1、直接在docker内替换jar包
2、直接用新版本docker覆盖，但这种方式需要把数据库指向外部mysql数据库

我不知道你更推荐哪一种，或者说，哪一种有硬伤（比如会发生数据或附件、图片的丢失）

**Comment by ruibaby** [comment]
@wellmoonloft 1. docker版是没有支持mysql的，只支持h2。2. 不管你怎么折腾，只要~/halo下的东西不删除，数据库和附件就都还在，3. 光替换jar包是不行的，里面还有lib和resource。 4. 不明白你为什么要用MySQL。

**Comment by wellmoonloft** [comment]
> @wellmoonloft 1. docker版是没有支持mysql的，只支持h2。2. 不管你怎么折腾，只要~/halo下的东西不删除，数据库和附件就都还在，3. 光替换jar包是不行的，里面还有lib和resource。 4. 不明白你为什么要用MySQL。

不是“必须”非要用mysql呀，只是我正好有一个阿里云的mysql可以用而已，目的还是为了日后升级，我本来想如果用了外部数据库，新版本出来之后直接重新部署新版本的镜像，改一下数据库指向就好了。。。

**Comment by ruibaby** [comment]
h2也可以，也有控制台，升级也方便，都是自动改表结构的，不用担心。就算新版本出来了，你构建容器的时候，加参数设置一下数据库用户名和密码就可以了。

**Comment by wellmoonloft** [comment]
> h2也可以，也有控制台，升级也方便，都是自动改表结构的，不用担心。就算新版本出来了，你构建容器的时候，加参数设置一下数据库用户名和密码就可以了。

好的，明白了，那我放心用了，只是我用docker装的，升级的时候就是需要覆盖jar lib resources一个文件两个文件夹，对吧。

**Comment by ruibaby** [comment]
@wellmoonloft 升级的时候你把容器删了重新建都行，只不过主题需要重新下载

**Comment by JohnNiang** [comment]
@ruibaby 建议分页(**page**)作为param进行传递，
