### ISSUE TITLE
能否支持将~/halo指向Volume位置，直接放在主机上

### ISSUE THREAD

**Issue by wellmoonloft** [ruibaby/halo#90]
这样一来使用docker部署和升级就更加便捷了，只用在Docker Compose里面配置路径+数据库用户名密码即可，升级的时候直接重新pull docker

**Comment by ruibaby** [comment]
@wellmoonloft 好主意，不过现在就是这么做的

**Comment by wellmoonloft** [comment]
> @wellmoonloft 好主意，不过现在就是这么做的

嗯嗯，之前是用daocloud部署的，所以映射文件夹一直没有生效，刚才自己敲了一遍命令，测试没问题了，这下彻底放心了～
