### ISSUE TITLE
API里面commentDate的格式能否改成YYMMDD HHMMSS

### ISSUE THREAD

**Issue by wellmoonloft** [ruibaby/halo#91]
这是一个小问题，实际上小程序端做一次格式转化也可以，
不过接口回来的信息里面：
postDate的格式是2019-02-02 02:14这样的
commentDate的格式是1549077179155这样的，
如果可以的话，下一个版本是否能统一成YYMMDD HHMMSS这样的呢？

**Comment by ruibaby** [comment]
@wellmoonloft 可以，post那边是有做的，comment那边忘了做。

**Comment by ruibaby** [comment]
@JohnNiang 现在改的话，以前的数据咋办

**Comment by JohnNiang** [comment]
@ruibaby 
目前所能想到的辦法：
> 添加一個新的字段，並將原有的時間轉換爲時間戳，最後設置到新的字段上。

```
postDate -> postTime
commentDate -> postTime
```

可以考慮在服務器重啓的時候進行遷移。如果穩定運行了，可考慮刪除 **postDate** 和 **commentDate** 。當然了，也可以一直保留。

**Comment by wellmoonloft** [comment]
> 用时间戳更加灵活，至于时间的显示格式就在前端进行处理即可，想怎么处理就怎么处理。

确实是可以的，不过因为接口返回的数据是个list，做转化的话还要循环取数，然后处理后再push进去，所以如果过来的话就处理好了是最好的

当然啦，也看作者是怎么想的，只要统一就好了，这样我可以统一转化一次。

**Comment by wellmoonloft** [comment]
> @wellmoonloft 可以，post那边是有做的，comment那边忘了做。

此外API里面还有一个值postThumbnail，这个是封面的缩略图地址，如果写文章的时候不选择，那么是默认的图片，这些图片的地址是类似upload/2019/1/cumstom_bg20190202113740219.jpg这样的，但是如果选择了图片的话，那么这里返回的值就是https://XXXXXX/upload/2019/1/cumstom_bg20190202113740219.jpg
带域名的，这个你看要不要改，如果不改的话在前端展现就还需要加一个判断，比如做个字符串查询域名，查不到的话就自行补充。

**Comment by ruibaby** [comment]
@wellmoonloft 所属问题均已修改。感谢你的反馈
