### ISSUE TITLE
修改登录密码

### ISSUE THREAD

**Issue by zoujiayu** [ruibaby/halo#93]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

![default](https://user-images.githubusercontent.com/20484791/52320738-ebc3df00-2a0b-11e9-9152-bfa6c042a828.PNG)
没有看到相关信息，是我操作太骚还是 /斜眼笑

**Comment by ruibaby** [comment]
操作太骚，鉴定完毕。
