### ISSUE TITLE
docker部署 nginx代理问题 求助

### ISSUE THREAD

**Issue by jianqiao0313** [ruibaby/halo#94]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [ ] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

## 我用docker部署的，有个域名( https://www.a.top )，现在想把 https://www.a.top/blog/ 指向本地的8090端口，nginx配置如下：
![image](https://user-images.githubusercontent.com/15814955/52837181-b6fd0980-3128-11e9-9ef8-26fce48f5309.png)
## 现在有个问题，访问https://www.a.top/blog/ 打开页面后，首页的链接不带blog这个路径的，如下图：
![image](https://user-images.githubusercontent.com/15814955/52837271-09d6c100-3129-11e9-9f1c-579b38fedc4d.png)
## 我的博客配置如下
![image](https://user-images.githubusercontent.com/15814955/52837480-dcd6de00-3129-11e9-9ea7-4d57153e6966.png)

> （注：根目录有应用。且https证书只是免费的，不支持blog.a.top这种路径）

**Comment by ruibaby** [comment]
外观 -> 菜单设置，改一下首页的地址：/ -> /blog

**Comment by jianqiao0313** [comment]
> 外观 -> 菜单设置，改一下首页的地址：/ -> /blog

谢谢，首页和归档的链接问题解决了。还有个问题，博客的路径能加上blog嘛？
现在直接是  https://www.a.top/archives/1550144013388 我想改成 https://www.a.top/blog/archives/1550144013388 如下图（底部的链接）
![image](https://user-images.githubusercontent.com/15814955/52847329-d30fa380-3146-11e9-957c-2079676cb0ec.png)
在文章设置里面，页面路径是对的，如下图
![image](https://user-images.githubusercontent.com/15814955/52847522-6943c980-3147-11e9-80a5-c9862b2cbffc.png)

**Comment by ruibaby** [comment]
@jianqiao0313 这个的话，只能改主题了，稍后上一个，你更新就行

**Comment by ruibaby** [comment]
@jianqiao0313 已经可以了，Anatole主题和Material主题，都使用的是绝对路径了，其他主题后续再改。
