### ISSUE TITLE
通过内置图库页面删除图片成功后报错 

### ISSUE THREAD

**Issue by myflytop** [ruibaby/halo#97]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
----

以下是报错内容
 when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: ${gallery.galleryId?c} [in template "admin/widget/_gallery-detail.ftl" at line 28, column 53] ---- Java stack trace (for programmers): ---- freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...] at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) at 

初步判断应该是重新请求了一次删除的图片信息导致的

**Comment by JohnNiang** [comment]
好的，等会儿去复现排查一下。

> 感谢您的反馈！

**Comment by ruibaby** [comment]
@myflytop 已修复，感谢您的反馈。
