### ISSUE TITLE
有什么使用api来实现博客的例子么?找了找只找到了那个小程序呢

### ISSUE THREAD

**Issue by zohar-soul** [ruibaby/halo#99]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
@zohar-soul 暂时没有

**Comment by zohar-soul** [comment]
@ruibaby 谢谢

**Comment by ruibaby** [comment]
@zohar-soul 可以用api来做单页应用的，你会的话可以试试，可以帮助更好的完善api
